name: audioplayers_android
description: Android implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 3.0.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_android
publish_to: none

flutter:
  plugin:
    implements: audioplayers
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin

dependencies:
  audioplayers_platform_interface:
    git:
      url: https://github.com/bahricanyesil/audioplayers.git
      ref: main
      path: packages/audioplayers_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

