name: audioplayers_linux
description: Linux implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 2.0.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_linux
publish_to: none

flutter:
  plugin:
    implements: audioplayers
    platforms:
      linux:
        pluginClass: AudioplayersLinuxPlugin

dependencies:
  audioplayers_platform_interface:
    git:
      url: https://github.com/bahricanyesil/audioplayers.git
      ref: main
      path: packages/audioplayers_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

